### ISSUE TITLE
ArrayIndexOutOfBoundsException errors

### ISSUE THREAD

**Issue by cybersonic** [cflint/CFLint#583] opened 2018-06-26 15:06 UTC
I am getting loads of the following error (with different indexes of course) in a scan of a client's source code:

```
Error: "java.lang.ArrayIndexOutOfBoundsException" Location: com.cflint.CFLint.process(CFLint.java:346)
com.cflint.exception.CFLintScanException: java.lang.ArrayIndexOutOfBoundsException
	at com.cflint.CFLint.process(CFLint.java:346)
	at com.cflint.CFLint.scan(CFLint.java:294)
	at com.cflint.CFLint.scan(CFLint.java:280)
	at com.cflint.CFLint.scan(CFLint.java:280)
	at com.cflint.CFLint.scan(CFLint.java:280)
	at com.cflint.CFLint.scan(CFLint.java:205)
	at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:65)
	at com.cflint.cli.CFLintCLI.execute(CFLintCLI.java:371)
	at com.cflint.cli.CFLintCLI.main(CFLintCLI.java:339)
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

What would be a good way to debug this error to be able to provide better information?

The command I am running is `java -jar ~/bin/CFLint-1.4.0-all.jar -folder .`

**Comment by ryaneberly** [comment] 2018-07-09 01:51
If you want to debug yourself, fire up com.cflint.cli.CFLintCLI in an IDE (Eclipse).

Or if you want help here, could you please give the next couple lines, the real cause at the lines shown after "Caused by: java.lang.ArrayIndexOutOfBoundsException".

**Comment by robertdmunn** [comment] 2018-07-20 18:00
Getting a similar error in a differe.nt location. Maybe a separate bug, but noting it here.

Error: "130" Location: com.cflint.CFLint.reportRule(CFLint.java:1378)
java.lang.ArrayIndexOutOfBoundsException: 130
        at com.cflint.CFLint.reportRule(CFLint.java:1378)
        at com.cflint.CFLint.scanExpression(CFLint.java:1022)
        at com.cflint.CFLint.process(CFLint.java:775)
        at com.cflint.CFLint.process(CFLint.java:867)
        at com.cflint.CFLint.process(CFLint.java:772)
        at com.cflint.CFLint.process(CFLint.java:515)
        at com.cflint.CFLint.processStack(CFLint.java:416)
        at com.cflint.CFLint.process(CFLint.java:476)
        at com.cflint.CFLint.processStack(CFLint.java:416)
        at com.cflint.CFLint.process(CFLint.java:629)
        at com.cflint.CFLint.processStack(CFLint.java:398)
        at com.cflint.CFLint.process(CFLint.java:341)
        at com.cflint.CFLint.scan(CFLint.java:294)
        at com.cflint.CFLint.scan(CFLint.java:280)
        at com.cflint.CFLint.scan(CFLint.java:280)
        at com.cflint.CFLint.scan(CFLint.java:280)
        at com.cflint.CFLint.scan(CFLint.java:280)
        at com.cflint.CFLint.scan(CFLint.java:205)
        at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:65)
        at com.cflint.cli.CFLintCLI.execute(CFLintCLI.java:371)
        at com.cflint.cli.CFLintCLI.main(CFLintCLI.java:339)

**Comment by CrazyPyro** [comment] 2018-08-29 22:09
I get this too on Win10 w/ JRE 8u181.  But it still produces a `cflint-result.html` with plenty of results.   I'm guessing there's a file somewhere in there that it doesn't know how to parse.   I'll check into it more on Linux tonight.

**Comment by ryaneberly** [comment] 2018-09-15 02:43
It looks like sometimes the attempt to determine the column is generating an outofbounds (and not reporting that error).  Wrapping the setColumn calculation with a try/catch.

**Comment by ryaneberly** [comment] 2018-09-15 02:44
fixed in dev branch.

**Closed by ryaneberly** 2018-09-15 02:44 UTC
Labels: bug
