### ISSUE TITLE
MISSING_VAR: Variable argumentCollection is not declared with a var statement.

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#552] opened 2018-03-29 01:26 UTC
```coldfusion
<cfscript>
private any function _preparePageObject( required string pageFilePath, required string rootDirectory ) {
		var page = "";
		var pageData = new PageReader().readPageFile( arguments.rootDirectory & pageFilePath );
		
			switch( pageData.pageType ?: "" ) {
				case "function":
					pageData.append( _getFunctionSpecification( pageData.slug, arguments.rootDirectory & pageFilePath ), false );
					page = new FunctionPage( argumentCollection**=pageData );
				break;
				case "tag":
					pageData.append( _getTagSpecification( pageData.slug, arguments.rootDirectory & pageFilePath ), false );
					page = new TagPage( argumentCollection=pageData );
				break;
				default:
					page = new Page( argumentCollection=pageData );
            }
  }
</cfscript>
```

snippet from https://github.com/lucee/lucee-docs/blob/master/api/data/DocTree.cfc#L231

**Comment by KamasamaK** [comment] 2018-03-29 01:53
Duplicate of #517

**Closed by KamasamaK** 2018-03-29 01:53 UTC
