### ISSUE TITLE
Not parsing array appends correctly.

### ISSUE THREAD

**Issue by rbreaves** [cflint/CFLint#698] opened 2021-01-07 23:11 UTC
Handles correctly.

```var testArray1 = arrayAppend( [], payload );```

Does not handle correctly.

```var testArray2 = [].append( payload );```

	"code": "MISSING_SEMI",
	"severity": 8,
	"message": "End of statement(;) expected after ]",
	"tags": []

**Comment by KamasamaK** [comment] 2021-01-08 01:13
Duplicate of #665

**Closed by KamasamaK** 2021-01-08 01:13 UTC
