### ISSUE TITLE
PARSE_ERROR Ordered Struct Syntax

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#557] opened 2018-04-14 03:22 UTC
```
var jsonLd = [
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement" = [
            [
            "@type":"ListItem",
            "position":1,
            "item": [
                "@id":"http://docs.lucee.org",
                "name":"Docs"
            ]
        ]
    ]
];
```

CFlint reports PARSE_ERROR for @context and @type, but oddly not @id 

http://docs.lucee.org/reference/functions/structnew.html

https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/using-arrays-and-structures/creating-and-using-structures.html#Creatingstructuresimplicitly

**Comment by KamasamaK** [comment] 2018-05-05 02:17
Duplicate of #534

**Closed by KamasamaK** 2018-05-05 02:17 UTC
