### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by royappa** [cflint/CFLint#273] opened 2017-05-31 07:51 UTC
Three failed tests are reported. I have added the mvn -v output first:

> Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T13:39:06-06:00)
> Maven home: /usr/local/src/apache-maven-3.5.0
> Java version: 1.7.0_141, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.141.x86_64/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "2.6.32-71.29.1.el6.x86_64", arch: "amd64", family: "unix"

The failed tests seem to all be the same problem:
> Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 4 sec <<< FAILURE! - in com.cflint.integration.TestIntegrationFolder
> test_194(com.cflint.integration.TestIntegrationFolder)  Time elapsed: 1.392 sec  <<< ERROR!
> java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 11
> \s"file".+\R
>            ^
>         at java.util.regex.Pattern.error(Pattern.java:1924)
>         at java.util.regex.Pattern.escape(Pattern.java:2416)
>         at java.util.regex.Pattern.atom(Pattern.java:2164)
>         at java.util.regex.Pattern.sequence(Pattern.java:2046)
>         at java.util.regex.Pattern.expr(Pattern.java:1964)
>         at java.util.regex.Pattern.compile(Pattern.java:1665)
>         at java.util.regex.Pattern.<init>(Pattern.java:1337)
>         at java.util.regex.Pattern.compile(Pattern.java:1022)
>         at java.lang.String.replaceAll(String.java:2162)
>         at com.cflint.integration.TestIntegrationFolder.test_194(TestIntegrationFolder.java:67)
> 
> testFolder(com.cflint.integration.TestIntegrationFolder)  Time elapsed: 1.379 sec  <<< ERROR!
> java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 11
> \s"file".+\R
>            ^
>         at java.util.regex.Pattern.error(Pattern.java:1924)
>         at java.util.regex.Pattern.escape(Pattern.java:2416)
>         at java.util.regex.Pattern.atom(Pattern.java:2164)
>         at java.util.regex.Pattern.sequence(Pattern.java:2046)
>         at java.util.regex.Pattern.expr(Pattern.java:1964)
>         at java.util.regex.Pattern.compile(Pattern.java:1665)
>         at java.util.regex.Pattern.<init>(Pattern.java:1337)
>         at java.util.regex.Pattern.compile(Pattern.java:1022)
>         at java.lang.String.replaceAll(String.java:2162)
>         at com.cflint.integration.TestIntegrationFolder.testFolder(TestIntegrationFolder.java:28)
> 
> testRuleGroupFolder(com.cflint.integration.TestIntegrationFolder)  Time elapsed: 1.217 sec  <<< ERROR!
> java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 11
> \s"file".+\R
>            ^
>         at java.util.regex.Pattern.error(Pattern.java:1924)
>         at java.util.regex.Pattern.escape(Pattern.java:2416)
>         at java.util.regex.Pattern.atom(Pattern.java:2164)
>         at java.util.regex.Pattern.sequence(Pattern.java:2046)
>         at java.util.regex.Pattern.expr(Pattern.java:1964)
>         at java.util.regex.Pattern.compile(Pattern.java:1665)
>         at java.util.regex.Pattern.<init>(Pattern.java:1337)
>         at java.util.regex.Pattern.compile(Pattern.java:1022)
>         at java.lang.String.replaceAll(String.java:2162)
>         at com.cflint.integration.TestIntegrationFolder.testRuleGroupFolder(TestIntegrationFolder.java:47)
>

**Comment by TheRealAgentK** [comment] 2017-06-01 04:32
I can't reproduce that on OS X with Java 1.8.0_92

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

I wonder if there's some difference in how RegEx behaviour is implemented between Java 7 and 8. 

My first suggestion would be to try running it on Java 8 and see what happens there and report back here.

Then re actual error:

Looking at the specific RegEx \\s\"file\".+\\R - my feeling is that it has some issue with the bit \\s and: 

\\ being the escaped backslash as well as 
\s being the predefined whitespace character class

Why that is an issue on your JVM and working fine here, I don't know, sorry.

**Comment by TheRealAgentK** [comment] 2017-06-01 04:35
Update: I wonder if it's the `\R` - support for it seems to have been introduced only in Java 8: http://www.regexguru.com/2014/05/new-regular-expression-features-in-java-8/

Maybe try to rewrite the RegEx without \R and see if you can get the code to compile - it might still fail the tests.

**Comment by TheRealAgentK** [comment] 2017-06-07 00:15
Any feedback @royappa

**Comment by royappa** [comment] 2017-06-07 04:03
Unfortunately I don't use Java much so I had a heck of a time installing the SDK, Maven and other dependencies even to get it running the tests. So from that backtrace I can't even tell which file to modify, exactly, I look in a couple but didn't find the offending line(s).

**Comment by TheRealAgentK** [comment] 2017-06-07 04:53
Try here:

https://github.com/cflint/CFLint/blob/master/src/test/java/com/cflint/integration/TestIntegrationFolder.java

Lines 68/69, the Regex in the last .replaceAll().

**Comment by TheRealAgentK** [comment] 2017-06-07 04:56
Actually, I think this problem with \R might already be fixed in the dev branch. Switch to that and try it, maybe.

**Comment by ryaneberly** [comment] 2017-06-10 12:42
@royappa 
  We need to make it clearer on the site.   But both maven and gradle builds are supported.  Maven was first, gradle is easier.

All you need for a successfully build are
java jdk (in your system path)
pull the CFLint repo.
from the repo, run **gradlew build**
You don't need to install gradle/maven the project will take care of pulling in all the deps.

**Comment by ryaneberly** [comment] 2017-06-16 15:15
closing.  reopen if you continue to have trouble.

**Closed by ryaneberly** 2017-06-16 15:15 UTC
Labels: question
