### ISSUE TITLE
MISSING_VAR misreported on code

### ISSUE THREAD

**Issue by lmajano** [cflint/CFLint#539] opened 2018-02-13 19:21 UTC
The following is valid syntax and misreported

```java
// Create HTTP object
var oHTTP = new HTTP(
	method 			= arguments.method,
	url 			= "#variables.serviceURL#/api/#variables.version#/#arguments.resource#",
	charset 		= "utf-8",
	timeout 		= arguments.timeout,
	throwOnError 	= false,
	redirect 		= true
);
```

**Comment by KamasamaK** [comment] 2018-02-13 19:39
Probably a duplicate of #517

**Comment by lmajano** [comment] 2018-02-13 19:46
Should I close?

**Closed** 2018-02-13 19:54 UTC
Labels: duplicate
