### ISSUE TITLE
Parse error for ordered struct

### ISSUE THREAD

**Issue by afurey0** [cflint/CFLint#671] opened 2020-03-04 19:43 UTC
I'm getting a parse error for ordered structs. CFLint version 1.4.1; CFParser version 2.8.0.

```cfml
variables.foobar = [
    "foo": "bar"
];
```

I see there are some similar issues, but they're marked as closed.

**Comment by KamasamaK** [comment] 2020-03-04 19:49
Duplicate of #534

The reason it's closed is because it's fixed in the latest snapshot. You can follow the build instructions if you'd like to try it.

**Closed by KamasamaK** 2020-03-04 19:49 UTC

**Comment by afurey0** [comment] 2020-03-09 19:08
Thanks for the response and explanation. I had simply tried to download the latest JAR from the releases page, but that was for version 1.4.1. I was able to build it, and now it's working perfectly.

**Comment by ryaneberly** [comment] 2020-03-11 00:57
1.5.0 is on maven now
