### ISSUE TITLE
wrong Parsing for new Object({})

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#669] opened 2020-02-27 13:55 UTC
Tested for UNUSED_LOCAL_VARIABLE.
LOCAL.myVar - is reported as unused.

```cfml
<cfcomponent>
    <cffunction name="actionList">
        <cfset LOCAL.myVar = test(
            argName = "test"
        )>
        <cfset  LOCAL.secondVar = new myObj({
            varName = LOCAL.myVar
        })>
    </cffunction>
</cfcomponent>
```

**Comment by KamasamaK** [comment] 2020-03-07 03:08
@Vintic Can you check again with the latest build? I think c4006c9 may have fixed this.

**Comment by Vintic** [comment] 2020-03-09 07:35
> @Vintic Can you check again with the latest build? I think [c4006c9](https://github.com/cflint/CFLint/commit/c4006c96f1f3a757f9c3f20a46c231a2aceb2c43) may have fixed this.

Yes, fixed, thanks you. Should I close issue?

**Comment by KamasamaK** [comment] 2020-03-09 08:02
I don't see why we would leave the issue opened if it's resolved. Also, duplicate of #640. I'll close it.

**Closed by KamasamaK** 2020-03-09 08:02 UTC

**Comment by ryaneberly** [comment] 2020-03-11 00:51
Thanks @KamasamaK
