### ISSUE TITLE
Returning incorrect version number

### ISSUE THREAD

**Issue by laserbyte** [cflint/CFLint#46] opened 2015-04-23 13:44 UTC
Both of the latest 0.4 releases return the incorrect version number:

https://github.com/cflint/CFLint/releases

    CFLint-0.4/target/appassembler/bin/cflint --version
    CFLint-CFLint-0.4-release/target/appassembler/bin/cflint -version

They both return this:

    CFLint 0.3.1-SNAPSHOT

**Comment by sdurette** [comment] 2015-04-23 13:49
Any chance you are on windows and have cflint set up somewhere else in your system as the default?  I had this issue because I had the final compiled program in one directory that was pointed to when cflint was called.  Copying over those files with the newer ones resolved the issue.

**Comment by laserbyte** [comment] 2015-04-23 13:55
Nope, I'm on Mac OS 10.8.5 and I don't have cflint in my path.

**Comment by jjames967** [comment] 2015-06-16 22:50
Closing as "works for me". If someone is able to reproduce, please open a new issue.

**Closed by jjames967** 2015-06-16 22:50 UTC
